Repository alphapapa/ement.el, pull requests merged in 2023-08, with the labels that each got.

#190 Fix room list display with empty notification actions
  README.org
  ement-lib.el
Labels: bug

#145 Add Guix package search link
  README.org
Labels: documentation

#164 Enable image-mode when displaying images in a new buffer
  README.org
  ement-room.el
Labels: enhancement
